version: "3.7"
services:
  synthium:
    image: node:19-alpine3.16
    container_name: synthium
    ports:
      - 5175:5173
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app
    command: sh -c "npm install && npm run dev"
    restart: always
